[package]
name = "coio"
version = "0.1.5"
authors = ["Y. T. Chung <zonyitoo@gmail.com>", "Leonard Hecker <leonard@hecker.io>"]
description = "Coroutine scheduler with non-blocking I/O support"
repository = "https://github.com/zonyitoo/coio-rs"
keywords = ["coroutine", "fiber", "green", "green thread", "non-blocking", "io", "async"]

[lib]
name = "coio"

[dev-dependencies]
clap = "*"
env_logger = "*"
num_cpus = "*"
rand = "*"
time = "*"

[dependencies]
chrono = "^0.2.15"
context = { git = "https://github.com/zonyitoo/context-rs.git" }
deque = "^0.2.3"
libc = "^0.1.10"
log = "^0.3.1"
mio = "^0.5.0"
rand = "^0.3.10"
net2 = "0.2.16"
